language: python
sudo: false
cache: pip
python:
- '2.7'
- '3.4'
env:
- REQ="Django>=1.10,<1.11"
- REQ="https://github.com/django/django/archive/stable/1.11.x.zip#egg=Django"
services:
- postgresql
install:
- pip install -U pip wheel
- pip install $REQ psycopg2 pytz
script: PYTHONWARNINGS=all PYTHONPATH=. ./cte_forest_test/manage.py test
